name: freebsd

on: [push, pull_request]

jobs:
  clang:
    # Run actions in a FreeBSD VM on the macos-12 runner
    # https://github.com/actions/runner/issues/385 - for FreeBSD runner support
    # https://github.com/actions/virtual-environments/issues/4060 - for lack of VirtualBox on MacOS 11 runners
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Test in FreeBSD VM
        uses: cross-platform-actions/action@v0.21.1
        timeout-minutes: 180
        with:
          operating_system: freebsd
          version: "13.2"
          environment_variables: CPPFLAGS=-isystem/usr/local/include LDFLAGS=-L/usr/local/lib
          run: |
            sudo sed -i '' 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
            sudo pkg install -y git #  subprojects/date
            sudo pkg install -y catch evdev-proto gtk-layer-shell gtkmm30 jsoncpp \
              libdbusmenu libevdev libfmt libmpdclient libudev-devd meson \
              pkgconf pulseaudio scdoc sndio spdlog wayland-protocols upower \
              libinotify
            meson build -Dman-pages=enabled
            ninja -C build
            meson test -C build --no-rebuild --print-errorlogs --suite waybar
